{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "Food_diary_Backend",
    "description": "web app about your calories"
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    { "url": "https://food-diary-backend-kr1b.onrender.com/api" },
    { "url": "http://localhost:3000/api" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "User",
      "description": "Users endpoints"
    },
    {
      "name": "Recommended food",
      "description": "Recommended food endpoints"
    }
  ],

  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "Sign up new user",
        "parameters": [],

        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequestResponse"
                }
              }
            }
          },
          "409": {
            "description": "Email already in use",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorConflictResponse"
                }
              }
            }
          }
        }
      }
    },
    "/auth/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "Sign in existing user",
        "parameters": [],
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequestResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorLoginResponse"
                }
              }
            }
          }
        }
      }
    },
    "/auth/signout": {
      "post": {
        "tags": ["Auth"],
        "summary": "Signs out user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "User signed out"
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          }
        }
      }
    },
    "/auth/forgot-password": {
      "post": {
        "tags": ["Auth"],
        "summary": "User forgot his password",
        "parameters": [],
        "requestBody": {
          "description": "User's email",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "description": "User's email",
                "required": ["email"],
                "properties": {
                  "email": {
                    "type": "string",
                    "description": "User's email",
                    "format": "email",
                    "example": "anna@mail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": "200"
                    },
                    "message": {
                      "type": "string",
                      "example": "Новий пароль відправлено на ваш email"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequestResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/current": {
      "get": {
        "tags": ["User"],
        "summary": "Get information about the current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Logged user returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequestResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/update": {
      "put": {
        "tags": ["User"],
        "summary": "Update profile settings",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Для оновлення інформації про користувача або одного з полів контактної інформації з перерахунком BMR/денної норми води/співвідношення макроелементів до BMR, у разі змін даних, що застосовуються у формулах",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/user/goal": {
      "put": {
        "tags": ["User"],
        "summary": "Update user goal",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "New user goal",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["goal"],
                "properties": {
                  "goal": {
                    "type": "string",
                    "enum": ["Lose Fat", "Maintain", "Gain Muscle"]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The goal has been updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/weight": {
      "post": {
        "tags": ["User"],
        "summary": "Create and update the user's current weight",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Current weight",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["weight"],
                "properties": {
                  "weight": {
                    "type": "number",
                    "example": 55
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The weight has been updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WeightResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/food-intake": {
      "post": {
        "tags": ["User"],
        "summary": "Information about consumed food",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Creates an object about the food eaten by the user for the current date",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FoodPostRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create foodIntake",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["User"],
        "summary": "Delete information about the consumed food of the corresponding meal for the current date ?????",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {},
        "responses": {
          "200": {
            "description": "Delete consumed food on current date",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/food-intake/{foodIntakeId}": {
      "put": {
        "tags": ["User"],
        "summary": "Update information about consumed food by identifier (foodIntakeId) ",
        "parameters": [
          {
            "in": "path",
            "name": "foodIntakeId",
            "required": "true",
            "type": "string",
            "description": "foodIntake's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Creates an object about the food eaten by the user for the current date",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FoodPostRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/water-intake": {
      "post": {
        "tags": ["User"],
        "summary": "Adding the water consumed by the user for the current date",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Value water",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["water"],
                "properties": {
                  "water": {
                    "type": "number",
                    "example": 200
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Adds consumed water and updates the volume",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WaterPostResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["User"],
        "summary": "Delete information about the consumed water for the current date",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Delete consumed water on current date",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WaterDeleteResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user/statistics": {
      "get": {
        "tags": ["User"],
        "summary": "Get statistics of the user for the selected period",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Selected period",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["month"],
                "properties": {
                  "month": {
                    "type": "string",
                    "example": "November"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Statistics of the user for the selected period",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StatisticsResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/recommended-food": {
      "get": {
        "tags": ["Recommended food"],
        "summary": "List of recommended products",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Get all recommended food",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayAllFoodResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": [
          "name",
          "password",
          "email",
          "goal",
          "gender",
          "age",
          "height",
          "weight",
          "activity"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Anna Smith"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "anna@mail.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "123456"
          },
          "goal": {
            "type": "string",
            "description": "User's goal",
            "enum": ["Lose Fat", "Maintain", "Gain Muscle"],
            "example": "Lose Fat"
          },
          "gender": {
            "type": "string",
            "description": "User's gender",
            "enum": ["female", "male"],
            "example": "female"
          },
          "age": {
            "type": "integer",
            "description": "User's age",
            "example": 32
          },
          "height": {
            "type": "integer",
            "description": "User's height",
            "example": 170
          },
          "weight": {
            "type": "integer",
            "description": "User's weight",
            "example": 55
          },
          "activity": {
            "type": "number",
            "description": "User's activity",
            "example": 1.2
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Anna Smith"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "123456"
          },
          "goal": {
            "type": "string",
            "description": "User's goal",
            "example": "Lose Fat"
          },
          "gender": {
            "type": "string",
            "description": "User's gender",
            "example": "female"
          },
          "age": {
            "type": "integer",
            "description": "User's age",
            "example": 32
          },
          "height": {
            "type": "integer",
            "description": "User's height",
            "example": 170
          },
          "weight": {
            "type": "integer",
            "description": "User's weight",
            "example": 55
          },
          "activity": {
            "type": "number",
            "description": "User's activity",
            "example": 1.2
          }
        },
        "example": {
          "user": {
            "name": "Anna Smith",
            "email": "anna@mail.com",
            "goal": "Maintain",
            "gender": "female",
            "age": 32,
            "height": 170,
            "weight": 55,
            "activity": 1.2
          }
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["password", "email"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "anna@mail.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "123456"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's token"
          },
          "user": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Anna Smith"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email",
                "example": "anna@mail.com"
              }
            }
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODJkMWM4NTk4ZmU5YjAzZDQ3NGQzYiIsImlhdCI6MTcwMzA3MjQ2OSwiZXhwIjoxNzAzMTU4ODY5fQ.bamDZbS_mGUq3T5w7CEqcLHBKcdUddnNDZdbhymgxHg",
          "user": {
            "name": "Anna Smith",
            "email": "anna@mail.com"
          }
        }
      },
      "CurrentResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Anna Smith"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "anna@mail.com"
          },

          "gender": {
            "type": "string",
            "description": "User's gender",
            "enum": ["female", "male"],
            "example": "female"
          },
          "age": {
            "type": "integer",
            "description": "User's age",
            "example": 32
          },
          "height": {
            "type": "integer",
            "description": "User's height",
            "example": 170
          },
          "weight": {
            "type": "integer",
            "description": "User's weight",
            "example": 55
          },
          "activity": {
            "type": "number",
            "description": "User's activity",
            "example": 1.2
          },
          "goal": {
            "type": "string",
            "enum": ["Lose Fat", "Maintain", "Gain Muscle"]
          },
          "recommendedFat": {
            "type": "number",
            "example": 1.2
          },
          "recommendedProtein": {
            "type": "number",
            "example": 517
          },
          "recommendedCarbs": {
            "type": "number",
            "example": 1421
          },
          "recommendedWater": {
            "type": "number",
            "example": 1.65
          },
          "recommendedCalories": {
            "type": "number",
            "example": 2584
          },
          "avatarURL": {
            "type": "string",
            "example": "https://cdn-icons-png.flaticon.com/256/805/805439.png"
          }
        },
        "example": {
          "email": "anna@mail.com",
          "name": "Anna Smith",
          "gender": "female",
          "weight": 55,
          "height": 170,
          "age": 32,
          "activity": 1.2,
          "goal": "Lose Fat",
          "recommendedFat": 323,
          "recommendedProtein": 403,
          "recommendedCarbs": 887,
          "recommendedWater": 1.65,
          "recommendedCalories": 1613,
          "avatarURL": "https://cdn-icons-png.flaticon.com/256/805/805439.png"
        }
      },
      "UpdateRequest": {
        "type": "object",
        "required": ["gender", "age", "height", "weight", "activity"],
        "properties": {
          "gender": {
            "type": "string",
            "description": "User's gender",
            "enum": ["female", "male"],
            "example": "female"
          },
          "age": {
            "type": "integer",
            "description": "User's age",
            "example": 32
          },
          "height": {
            "type": "integer",
            "description": "User's height",
            "example": 170
          },
          "weight": {
            "type": "integer",
            "description": "User's weight",
            "example": 55
          },
          "activity": {
            "type": "number",
            "description": "User's activity",
            "example": 1.2
          }
        }
      },
      "UpdateResponse": {
        "type": "object",
        "properties": {
          "-_id": {
            "type": "string",
            "description": "User's id",
            "example": "6580d675b14c4b0dfc51fecc"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Anna Smith"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "123456"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "anna@mail.com"
          },
          "goal": {
            "type": "string",
            "description": "User's goal",
            "enum": ["Lose Fat", "Maintain", "Gain Muscle"],
            "example": "Lose Fat"
          },
          "gender": {
            "type": "string",
            "description": "User's gender",
            "enum": ["female", "male"],
            "example": "female"
          },
          "age": {
            "type": "integer",
            "description": "User's age",
            "example": 32
          },
          "height": {
            "type": "integer",
            "description": "User's height",
            "example": 170
          },
          "weight": {
            "type": "integer",
            "description": "User's weight",
            "example": 55
          },
          "activity": {
            "type": "number",
            "description": "User's activity",
            "example": 1.2
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODJkMWM4NTk4ZmU5YjAzZDQ3NGQzYiIsImlhdCI6MTcwMzA3MjQ2OSwiZXhwIjoxNzAzMTU4ODY5fQ.bamDZbS_mGUq3T5w7CEqcLHBKcdUddnNDZdbhymgxHg"
          },
          "avatarURL": {
            "type": "string",
            "example": "https://cdn-icons-png.flaticon.com/256/805/805439.png"
          },
          "recommendedFat": {
            "type": "number",
            "example": 1.2
          },
          "recommendedProtein": {
            "type": "number",
            "example": 517
          },
          "recommendedCarbs": {
            "type": "number",
            "example": 1421
          },
          "recommendedWater": {
            "type": "number",
            "example": 1.65
          },
          "recommendedCalories": {
            "type": "number",
            "example": 2584
          },
          "createdAt": {
            "type": "string",
            "example": "2023-12-18T23:32:05.818Z"
          },
          "updatedAt": {
            "type": "string",
            "example": "2023-12-18T23:56:08.118Z"
          }
        },
        "example": {
          "_id": "6580d675b14c4b0dfc51fecc",
          "name": "Anna",
          "password": "$2a$10$Lq1FWAFWvqiGWFE71cH1Pe4hU9gHm4OBbkuI8NuIh0ilyDm6C8rwq",
          "email": "anna@mail.com",
          "goal": "Maintain",
          "gender": "female",
          "age": 32,
          "height": 175,
          "weight": 65,
          "activity": 1.3,
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODBkNjc1YjE0YzRiMGRmYzUxZmVjYyIsImlhdCI6MTcwMjk0MjM0NCwiZXhwIjoxNzAzMDI4NzQ0fQ.vvAOcHEjpxFwc2m0kHtgw6Q3fBV_yHdnd0z0_8jWT9w",
          "avatarURL": "https://cdn-icons-png.flaticon.com/256/805/805439.png",
          "recommendedFat": 472,
          "recommendedProtein": 378,
          "recommendedCarbs": 1038,
          "recommendedWater": 1.95,
          "recommendedCalories": 1888,
          "createdAt": "2023-12-18T23:32:05.818Z",
          "updatedAt": "2023-12-18T23:56:08.118Z"
        }
      },
      "WeightResponse": {
        "type": "object",
        "properties": {
          "type": "object",
          "description": "New weight",
          "properties": {
            "-_id": {
              "type": "string",
              "description": "User's id",
              "example": "6580d675b14c4b0dfc51fecc"
            },
            "weights": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "number",
                  "description": "New weight",
                  "example": 55
                }
              }
            },
            "owner": {
              "type": "string",
              "description": "User's id",
              "example": "6582d1c8598fe9b03d474d3b"
            },
            "__v": {
              "type": "number",
              "description": "object version",
              "example": 0
            }
          }
        },
        "example": {
          "_id": "6582d1c8598fe9b03d474d3d",
          "weights": {
            "2023-12-20": 55
          },
          "owner": "6582d1c8598fe9b03d474d3b",
          "__v": 0
        }
      },
      "WaterPostResponse": {
        "type": "object",
        "properties": {
          "type": "object",
          "description": "New value water",
          "properties": {
            "-_id": {
              "type": "string",
              "description": "User's id",
              "example": "6582fa0045d5b370656133f2"
            },
            "waters": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "number",
                  "description": "total volume of water drunk",
                  "example": 1500
                }
              }
            },
            "owner": {
              "type": "string",
              "description": "User's id",
              "example": "6582d1c8598fe9b03d474d3b"
            }
          }
        },
        "example": {
          "_id": "6582fa0045d5b370656133f2",
          "owner": "6582d1c8598fe9b03d474d3b",
          "waters": {
            "2023-12-20": 1500
          }
        }
      },
      "WaterDeleteResponse": {
        "type": "object",
        "properties": {
          "type": "object",
          "description": "New value water",
          "properties": {
            "-_id": {
              "type": "string",
              "description": "User's id",
              "example": "6582fa0045d5b370656133f2"
            },
            "waters": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "number",
                  "description": "total volume of water drunk",
                  "example": 0
                }
              }
            },
            "owner": {
              "type": "string",
              "description": "User's id",
              "example": "6582d1c8598fe9b03d474d3b"
            }
          }
        },
        "example": {
          "_id": "6582fa0045d5b370656133f2",
          "owner": "6582d1c8598fe9b03d474d3b",
          "waters": {
            "2023-12-20": 0
          }
        }
      },
      "FoodPostRequest": {
        "type": "object",
        "properties": {
          "Meal": {
            "type": "object",
            "description": "food intake",
            "properties": {
              "name": {
                "type": "string",
                "enum": ["breakfast", "lunch", "dinner", "snack"],
                "example": "breakfast"
              },
              "dish": {
                "type": "array",
                "description": "The name of the product or dish",
                "items": {
                  "type": "object",
                  "description": "?????",
                  "properties": {
                    "name": {
                      "type": "string",
                      "example": "tomato"
                    },
                    "calories": {
                      "type": "number",
                      "example": 52
                    },
                    "carbohydrates": {
                      "type": "number",
                      "example": 14
                    },
                    " protein": {
                      "type": "number",
                      "example": 0.3
                    },
                    "fat": {
                      "type": "number",
                      "example": 0.2
                    }
                  }
                }
              },
              "totalCalories": {
                "type": "number",
                "example": 0.3
              },
              "totalCarbs": {
                "type": "number",
                "example": 0.3
              },
              "totalProtein": {
                "type": "number",
                "example": 0.3
              },
              "totalFat": {
                "type": "number",
                "example": 0.3
              }
            }
          }
        },
        "example": {
          "breakfast": {
            "dish": [
              {
                "name": "tomato",
                "carbonohidrates": 30,
                "protein": 25,
                "fat": 23,
                "calories": 750
              }
            ],
            "totalCalories": 750,
            "totalCarbs": 30,
            "totalProtein": 25,
            "totalFat": 23
          }
        }
      },
      "FoodResponse": {
        "type": "object",
        "properties": {
          "Meal": {
            "type": "object",
            "description": "food intake",
            "properties": {
              "name": {
                "type": "string",
                "enum": ["breakfast", "lunch", "dinner", "snack"],
                "example": "breakfast"
              },
              "dish": {
                "type": "array",
                "description": "The name of the product or dish",
                "items": {
                  "type": "object",
                  "description": "?????",
                  "properties": {
                    "name": {
                      "type": "string",
                      "example": "tomato"
                    },
                    "calories": {
                      "type": "number",
                      "example": 52
                    },
                    "carbohydrates": {
                      "type": "number",
                      "example": 14
                    },
                    " protein": {
                      "type": "number",
                      "example": 0.3
                    },
                    "fat": {
                      "type": "number",
                      "example": 0.2
                    }
                  }
                }
              },
              "totalCalories": {
                "type": "number",
                "example": 0.3
              },
              "totalCarbs": {
                "type": "number",
                "example": 0.3
              },
              "totalProtein": {
                "type": "number",
                "example": 0.3
              },
              "totalFat": {
                "type": "number",
                "example": 0.3
              }
            }
          }
        },
        "example": {
          "breakfast": {
            "dish": [
              {
                "name": "tomato",
                "carbonohidrates": 30,
                "protein": 25,
                "fat": 23,
                "calories": 750,
                "_id": "6583113b9bf7bfe2eed406ef"
              }
            ],
            "totalCalories": 750,
            "totalCarbs": 30,
            "totalProtein": 25,
            "totalFat": 23
          },
          "lunch": {
            "dish": [],
            "totalCalories": 0,
            "totalCarbs": 0,
            "totalProtein": 0,
            "totalFat": 0
          },
          "dinner": {
            "dish": [],
            "totalCalories": 0,
            "totalCarbs": 0,
            "totalProtein": 0,
            "totalFat": 0
          },
          "snack": {
            "dish": [],
            "totalCalories": 0,
            "totalCarbs": 0,
            "totalProtein": 0,
            "totalFat": 0
          },
          "totalCalories": 750,
          "totalCarbs": 30,
          "totalProtein": 25,
          "totalFat": 23,
          "owner": "6582d1c8598fe9b03d474d3b",
          "_id": "6583113b9bf7bfe2eed406ee",
          "date": "2023-12-20"
        }
      },
      "StatisticsResponse": {
        "type": "object",
        "properties": {
          "Stats": {
            "type": "array",
            "description": "Statistic of the user per day",
            "items": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "string",
                  "example": "2023-11-01"
                },
                "water": {
                  "type": "number",
                  "example": 1550
                },
                "weight": {
                  "type": "number",
                  "example": 55
                },
                "totalCalories": {
                  "type": "number",
                  "example": 1800
                }
              }
            }
          }
        },
        "example": {
          "stats": [
            {
              "date": "2023-11-01",
              "water": 1550,
              "weight": 55,
              "totalCalories": 1800
            },
            {
              "date": "2023-11-02",
              "water": 1350,
              "weight": 0,
              "totalCalories": 1700
            },
            {
              "date": "2023-11-03",
              "water": 1400,
              "weight": 0,
              "totalCalories": 1950
            }
          ]
        }
      },

      "ErrorBadRequestResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "Error status code",
            "example": "400"
          },
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "Bad request"
          }
        }
      },
      "ErrorConflictResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "Error status code",
            "example": "409"
          },
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "User with email - user@example.com, already exist"
          }
        }
      },
      "ErrorUnauthorizedResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "Error status code",
            "example": "401"
          },
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "Not authorized"
          }
        }
      },
      "ErrorLoginResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "Error status code",
            "example": "401"
          },
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "Email or password invalid"
          }
        }
      },
      "ErrorNotFoundResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "Error status code",
            "example": "404"
          },
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "Not found"
          }
        }
      },

      "ArrayAllFoodResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "description": "All recommended food",
          "properties": {
            "name": {
              "type": "string",
              "example": "Apples"
            },
            "amount": {
              "type": "string",
              "example": "100 g"
            },
            "img": {
              "type": "string",
              "example": "https://ftp.goit.study/img/you_health/Apples.png"
            },
            "calories": {
              "type": "number",
              "example": 52
            },
            "nutrition": {
              "type": "object",
              "properties": {
                "carbohydrates": {
                  "type": "number",
                  "example": 14
                },
                " protein": {
                  "type": "number",
                  "example": 0.3
                },
                "fat": {
                  "type": "number",
                  "example": 0.2
                }
              }
            }
          }
        },
        "example": [
          {
            "name": "Apples",
            "amount": "100 g",
            "img": "https://ftp.goit.study/img/you_health/Apples.png",
            "calories": 52,
            "nutrition": {
              "carbohydrates": 14,
              "protein": 0.3,
              "fat": 0.2
            }
          },
          {
            "name": "Strawberries",
            "amount": "100 g",
            "img": "https://ftp.goit.study/img/you_health/Strawberries.png",
            "calories": 32,
            "nutrition": {
              "carbohydrates": 7.68,
              "protein": 0.67,
              "fat": 0.3
            }
          }
        ]
      }
    },

    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
